version: '2'
services:
  web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      DATABASE_URL: "postgres://postgres:Passw0rd!@db:5432/postgres"
    depends_on:
      - db
    networks:
      - external
      - internal
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD: /run/secrets/pg_pass
    secrets:
      - pg_pass
    networks:
      - internal
networks:
  internal:
  external:
    external: true
secrets:
  pg_pass:
    file: ./my_secret.txt
